### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by alexnofoget** [jeremyramin/terminal-plus#3]
**Atom Version**: 1.0.11
**System**: Linux Mint
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.1.3

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /home/alex/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:1307

TypeError: Cannot read property '0' of undefined
  at Terminal.refresh (/home/alex/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:1307:18)
  at Terminal.showCursor (/home/alex/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:1433:10)
  at Terminal.focus (/home/alex/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:474:8)
  at TerminalPlusView.module.exports.TerminalPlusView.focusTerminal (/home/alex/.atom/packages/terminal-plus/lib/view.coffee:295:15)
  at /home/alex/.atom/packages/terminal-plus/lib/view.coffee:188:10
  at HTMLDivElement.<anonymous> (/home/alex/.atom/packages/terminal-plus/lib/view.coffee:325:7)
  at HTMLDivElement.fn (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4855:19)
  at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -7:41.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:35.3.0 core:save (atom-text-editor.editor.is-focused)
     -4:51.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:59.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:44.3.0 core:copy (atom-text-editor.editor.is-focused)
     -1:33.5.0 core:paste (atom-text-editor.editor.is-focused)
     -1:16.8.0 core:copy (atom-text-editor.editor.is-focused)
     -1:12.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:12.4.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:57.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "terminal-plus": {
    "core": {},
    "style": {}
  }
}
```

### Installed Packages

```coffee
# User
react, v0.12.6
react-snippets, v0.2.0
terminal-plus, v0.1.3

# Dev
No dev packages
```

**Comment by jeremyramin** [comment]
@alexnofoget Sorry, I haven't had much chance to test this on other platforms yet. Thank you for taking the time to report this, I'll try and see what could be wrong.

**Comment by jeremyramin** [comment]
Fix should be fixed by commit c4ee1b8fc64f8df0eeae599f34bca27d53414c14.

**Comment by danieltdt** [comment]
I still getting this error

**Atom Version**: 1.0.11
**System**: linux 4.1.6-1-ARCH
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.2.0


### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /home/daniel/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:1307

TypeError: Cannot read property '0' of undefined
  at Terminal.refresh (/home/daniel/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:1307:18)
  at Terminal.write (/home/daniel/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:2578:8)
  at /home/daniel/.atom/packages/terminal-plus/lib/view.coffee:109:17
  at Task.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/task.js:79:31)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at handleMessage (child_process.js:306:10)
  at Pipe.channel.onread (child_process.js:334:11)

```

### Commands

```
  2x -3:45.1.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -3:44.6.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -3:44.1.0 vim-mode:change (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -3:44.1.0 vim-mode:select-inside-word (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -3:43.4.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 12x -3:43.2.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:41.7.0 vim-mode:change (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:41.7.0 vim-mode:select-inside-word (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -3:40.8.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -3:40.7.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -3:40.1.0 vim-mode:reverse-search (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:40.1.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:39.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -3:39.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -3:38.2.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 72x -3:36.8.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true,
    "projectHome": "/home/daniel/workspace",
    "disabledPackages": [
      "atom-pair"
    ]
  },
  "terminal-plus": {
    "core": {},
    "style": {}
  }
}
```

### Installed Packages

```coffee
# User
language-haml, v0.21.0
motepair, v0.20.0
terminal-plus, v0.2.0
vim-mode, v0.60.0
vim-mode-visual-block, v0.2.13
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by jeremyramin** [comment]
@danieltdt Thanks for the report. Could you tell me what command you were using when this happened? I need to look into it so I can try to reproduce the error and debug it.

**Comment by danieltdt** [comment]
I was running `bundle exec rails server`. I clicked on "Maximize" to check some requests then clicked on "Hide". After that, the error appears.
I was with other two terminals opened too, but nothing were running.

**Comment by jeremyramin** [comment]
@danieltdt Thanks! I'll look into this and get back to you.

**Comment by jeremyramin** [comment]
@danieltdt  New update. Please let me know if your issue was fixed.

**Comment by danieltdt** [comment]
Nice! I'll check this out. Thanks!

**Comment by jeremyramin** [comment]
Closing this issue because it has been two days since any reported issues.
